### ISSUE TITLE
Problem with GDAL installation

### ISSUE THREAD

**Issue by Mykins1994** [SMByC/Coregistration-Qgis-processing#11]
Hello,
I´m trying to run the Automated local Co-Registration in Qgis environment, but it gives me the following error:

Traceback (most recent call last):
File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\Coregistration\automated_local_coregistration_algorithm.py", line 274, in processAlgorithm
CRL = COREG_LOCAL(img_ref, img_tgt, path_out=output_file, align_grids=align_grids, match_gsd=match_gsd,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.3\apps\qgis\python\Coregistration\extlibs_windows\arosics\CoReg_local.py", line 329, in __init__
self.COREG_obj = COREG(self.imref, self.im2shift,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.3\apps\qgis\python\Coregistration\extlibs_windows\arosics\CoReg.py", line 413, in __init__
self._get_image_params()
File "C:\PROGRA~1\QGIS33~1.3\apps\qgis\python\Coregistration\extlibs_windows\arosics\CoReg.py", line 548, in _get_image_params
self.shift = GeoArray_CoReg(self.params, 'shift')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.3\apps\qgis\python\Coregistration\extlibs_windows\arosics\CoReg.py", line 120, in __init__
_ = self.footprint_poly # execute getter
^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.3\apps\qgis\python\Coregistration\extlibs_windows\geoarray\baseclasses.py", line 497, in footprint_poly
multipolygon = raster2polygon(self.mask_nodata.astype(np.uint8), self.gt, self.prj, exact=False,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.3\apps\qgis\python\Coregistration\extlibs_windows\py_tools_ds\geo\raster\conversion.py", line 86, in raster2polygon
array, gt, prj = warp_ndarray(array, gt, prj,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.3\apps\qgis\python\Coregistration\extlibs_windows\py_tools_ds\geo\raster\reproject.py", line 456, in warp_ndarray
res_ds = gdal.Warp(
^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\osgeo\gdal.py", line 1154, in Warp
return wrapper_GDALWarpDestName(destNameOrDestDS, srcDSTab, opts, callback, callback_data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\osgeo\gdal.py", line 8999, in wrapper_GDALWarpDestName
return _gdal.wrapper_GDALWarpDestName(*args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: in method 'wrapper_GDALWarpDestName', argument 4 of type 'GDALWarpAppOptions *'

Do you know which can be the issue?

**Comment by XavierCLL** [comment]
Hi @Mykins1994 thanks for your report.

@danschef: I think this issue is because Arosics and its libs are not completely compatible with Python 3.12. Are the latest versions of Arosics and its libs already fixed for Python 3.12? or what do you think?

Regards.

**Comment by danschef** [comment]
@Mykins1994 @XavierCLL  
Python 3.12 support was added in AROSICS v1.11.0, see the [changelog](https://git.gfz-potsdam.de/danschef/arosics/-/blob/main/HISTORY.rst?ref_type=heads). However, please note, that `py_tools_ds` (a requirement of arosics) now requires `gdal>=3.8`. The latest release of py_tools_ds (v0.22.2) also fixes [a similar RuntimeError](https://git.gfz-potsdam.de/danschef/arosics/-/issues/110) within the image warping that showed up in combination with gdal 3.9.

**Comment by XavierCLL** [comment]
Thanks so much @danschef 

@Mykins1994 please test with the latest version of the plugin v24.6

**Comment by XavierCLL** [comment]
@Mykins1994 I tested in Windows and I realized that for old version of Qgis the plugin has problems with the numpy and gdal version as Daniel mention, with the update v24.6.1 I restrict the plugin to Qgis => 3.34, I recommend you to use it at least that current LTR version
